# Common configuration shared between all applications
server:
  port: ${HTTP_PORT:8083}
  servlet:
    context-path: /procedure-service
  error:
    include-message: always
  shutdown: graceful

spring:
  application:
    name: procedure-service
  config:
    use-legacy-processing: true
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://gedoc-postgres.cobctxxlaup3.eu-west-1.rds.amazonaws.com:5432/postgres?currentSchema=sipad_cessazione}
    username: ${DATASOURCE_USER:postgres}
    password: ${DATASOURCE_PWD:Almaviva1234!}
    driver-class-name: ${DB_CLASS_DRIVER:org.postgresql.Driver}
    hikari:
      pool-name: ${HIKARI_POOL_NAME:hikari-proc}
      auto-commit: false
      idle-timeout: 60000 # 1 min - Maximum amount of time that a connection can to sit idle in the pool
      maximum-pool-size: 10
      minimum-idle: 5
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  liquibase:
    contexts: ${LIQUIBASE_CONTEXTS:dev}
    change-log: classpath:config/liquibase/master.xml
    enabled: ${LIQUIBASE_ENABLED:false}
    drop-first: false
  jpa:
    open-in-view: false
    database: default
    properties:
      hibernate:
        jdbc.fetch_size: 25
        jdbc.batch_size: 25
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        query.fail_on_pagination_over_collection_fetch: true
        query.in_clause_parameter_padding: true
        format_sql: false
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: ${SHOW_SQL:false}
  rabbitmq: # Indirizzo del server e credenziali di accesso a rabbitMQ
    host: ${RABBITMQ_HOST:sipad-centrale.rabbit-system.app.gedocc.giottolabs.com}
    username: ${RABBITMQ_USERNAME:3-cszimp}
    password: ${RABBITMQ_PASSWORD:v2LLF97GVV9uYCT}
    listener:
      simple:
        auto-startup: ${RABBIT_LISTENER_AUTO_STARTUP:true}

# Identificativo del prefisso delle code, composto dall'ID del verticale e l'acronimo registrato sul sipad
queuehelper.verticale: ${RABBITMQ_VERTICALE:3-cszimp}
isAdhocMock: ${ADHOC_MOCK_ENABLE:false}
queue: ${QUEUE_ENABLE:true}

app:
  idApplicativo: 3
  idApplicativoCentral: 3
  cors:
    allowed-origins: ${CORS_ORIGINS:*}
    allowed-methods: ${CORS_METHODS:*}
    allowed-headers: ${CORS_HEADERS:*}
    max-age: ${CORS_MAXAGE:3600}
  shedlock:
    automaticProtocolStatusShedMinutes: ${SHEDLOCK_CRON:0 */15 * * * *}
    automaticProtocolStatusShedLockAtLeastFor: ${SHEDLOCK_AT_LEAST_FOR:5m}
    automaticProtocolStatusShedLockAtMostFor: ${SHEDLOCK_AT_MOST_FOR:14m}

spring.zipkin.enabled: ${ZIPKIN_ENABLED:false}
spring.zipkin.base-url: ${ZIPKIN_BASE_URL:http://zipkin-server:9411}

cache: # Cache configuration
  ehcache: # Ehcache configuration
    time-to-live-seconds: 3600 # By default, objects stay 1 hour in the cache
    max-entries: 100 # Number of objects in each cache entry

logging:
  file:
    path: ${LOGGING_PATH:./logs}
    name: ${LOGGING_NAME:logs/${spring.application.name}.log}
  logback:
    rollingpolicy:
      max-history: ${LOGGING_HISTORY:5}
      max-file-size: ${LOGGING_MAX_SIZE:10MB}
  pattern:
    console: "%-30(%d{dd-MM-yyyy HH:mm:ss.SSS} %highlight(%-5level) %magenta([%thread]) %cyan(%logger{10}) %yellow([%file:%line]) : %msg%throwable%n)"
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} %-5level [%thread] %logger{10} [%file:%line] : %msg%throwable%n"
    
file.extn.list: ${FILE_EXTN_LIST:doc,docx,xls,xlsx,ppt,pptx,pdf,txt,xml}

adhoc:
  base-url: ${ADHOC_SERVICE_URL:http://adhoc-mock:8080/ADHOCMock/rest/service}
  username: ${ADHOC_SERVICE_USER:test_rds}
  header:
    password-key: ${ADHOC_PWD_KEY:password}
    password-value: ${ADHOC_HEADER_PWD:5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8}
    consumer-code-key: ${ADHOC_CONSUMER_CODE_KEY:consumercode}
    consumer-code-value: ${ADHOC_CONSUMER_CODE_VALUE:TEST}
    token-key: ${ADHOC_TOKEN_KEY:sessionToken}
  regex:
    register: ${ADHOC_REGEX_REGISTER:(?<=\s)[a-zA-Z]+?(?=[0-9])}
    numProtocol: ${ADHOC_REGEX_NUM_PROTOCOL:(?<=\s)[0-9]+?(?=\s)}
    date: ${ADHOC_REGEX_DATE:(?<=\s)(?=\S*$)[0-9].+$}
    year: ${ADHOC_REGEX_YEAR:(?<=-[0-9].{2}).+$}
    month: ${ADHOC_REGEX_MONTH:(?<=-)[0-9]+?(?=-)}
    day: ${ADHOC_REGEX_DAY:(?<=\s)[0-9]+?(?=-)}


application:
  adhoc:
    base-url: ${ADHOC_SERVICE_URL:http://sipad-mock.be.app.gedocc.giottolabs.com/adhoc-mock}
  auth-service:
    baseurl: ${AUTH_SERVICE_URL:http://sipad-cessazione.be.app.gedocc.giottolabs.com/auth-service}
  camunda:
    baseurl: ${CAMUNDA_SERVICE_URL:http://sipad-camunda.app.gedocc.giottolabs.com/engine-rest}
    processKey: cessazione_process
    tenant-id: ${CAMUNDA_TENANT_ID:cessazione}
    processDefinitionPath: /process-definition
    processInstancePath: /process-instance
    taskPath: /task
    decisionDefinitionPath: /decision-definition
    stateDecisionKey: stateDecisionKey
    roleDecisionKey: roleDecisionKey
    openingDataVisibilityKey: openingDataDecisionKey
    dichiarazioniDecisionKey: dichiarazioniDecisionKey
    leaveDecisionKey: congedoSpettanteDecisionKey
    transitDataDecisionKey: datiTransitoDecisionKey
    pensionDataDecisionKey: datiPensionisticiDecisionKey
    gmlDecisionKey: gmlDecisionKey
    documentActionsByProcDecisionKey: documentActionsByProcDecisionKey
    documentActionsByDocDecisionKey: documentActionsByDocDecisionKey
    rwOpeningDataDecisionKey: rwOpeningDataDecisionKey
    rwDomicilioElettoDecisionKey: rwDomicilioElettoDecisionKey
    rwDichiarazioniDecisionKey: rwDichiarazioniDecisionKey
    rwDatiTransitoDecisionKey: rwDatiTransitoDecisionKey
    rwDatiPensionisticiDecisionKey: rwDatiPensionisticiDecisionKey
    rwParereRagioneriaDecisionKey: rwParereRagioneriaDecisionKey
    congedoSpettanteDecisionKey: congedoSpettanteDecisionKey
    documentAdhocNegativeOutcomeDecisionKey: documentAdhocNegativeOutcomeDecisionKey
    reassignmentDecisionKey: reassignmentDecisionKey
  template-api:
    baseurl: ${TEMPLATE_API_URL:http://sipad-cessazione.be.app.gedocc.giottolabs.com/template-api}

ms-sipad-api:
  baseurl: ${MS_SIPAD_API_URL:http://sipad-cessazione.be.app.gedocc.giottolabs.com/ms-sipad-api}

centrale-api:
  baseurl: ${CENTRALE-API_URL:http://sipad-centrale.be.app.gedocc.giottolabs.com/centrale-api}

